package _004_Expressions;

import org.junit.jupiter.api.Test;

//DO NOT EDIT THIS FILE

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

// --tests ExpressionsTest.testExpressionsHomework()
class ExpressionsTest {
    @Test void testExpressionsHomework() {
    	ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ExpressionsHomework.main(null);

        String expectedOutput = "Questions attempted : 11, out of 11";
        String input = outContent.toString();
        String ending = input.substring(input.length()-35);
        		

        assertEquals(expectedOutput,ending);
    }
}
